version: '3.8'

services:
  strapi_backend:
    build:
      context: .
      dockerfile: Dockerfile.strapi
    container_name: strapi_backend
    restart: always
    environment:
      NODE_ENV: production
    volumes:
      - ./app:/app
      - sqlite-data:/app/.tmp # Persist SQLite database
    ports:
      - "1337:1337"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - strapi_backend

volumes:
  sqlite-data:

