# Use official Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json yarn.lock ./
RUN yarn install --fronzend-lockfile

# Copy the entire project
COPY . .

# Build TypeScript project
RUN yarn build

# Expose port 1337
EXPOSE 1337

# Start Strapi
CMD ["yarn", "start"]